# Generated by Django 4.2.16 on 2024-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='house',
            field=models.CharField(choices=[('Gryffindor', 'Gryffindor'), ('Slytherin', 'Slytherin'), ('Ravenclaw', 'Ravenclaw'), ('Hufflepuff', 'Hufflepuff')], max_length=50, verbose_name='Casa de Hogwarts'),
        ),
    ]
